language: minimal
sudo: required
services:
  - docker
matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode10.1
script:
  - ./run-in-docker.sh make dep install test
deploy:
  skip_cleanup: true
  provider: script
  script: ./run-release.sh $TRAVIS_TAG
  on:
    tags: true
