language: minimal
sudo: required
services:
  - docker

before_install:
  - [[ "$TRAVIS_OS_NAME" == "osx" ]] && ./build/macos-install-deps.sh

script:
  - [[ "$TRAVIS_OS_NAME" == "osx" ]] && make install test
  - [[ "$TRAVIS_OS_NAME" == "linux" ]] && ./run-in-docker.sh make dep install test

deploy:
  skip_cleanup: true
  provider: script
  script: ./run-release.sh $TRAVIS_TAG
  on:
    tags: true
